error corrected (v2.0)

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -1,5 +1,20 @@
 #!/bin/bash
 
+failureMessage(){
+   if [ $? -eq 0 ]
+   then
+      echo "----------------------------"
+      echo "$1 completed successfully."
+      echo "----------------------------"
+   else
+      echo "----------------------------"
+      echo "$1 FAILED."
+      echo "----------------------------"
+      exit
+   fi
+}
+
+
 set -e
 
 make
@@ -21,6 +36,7 @@ git clone --recursive https://github.com/GATB/dsk.git
 # compile the code an run a simple test on your computer
 cd dsk
 sh INSTALL
+failureMessage DSK_installation
 echo $PWD
 ln build/bin/dsk ../../bin/dskESS
 ln build/bin/dsk2ascii ../../bin/dsk2asciiESS
@@ -30,16 +46,19 @@ echo "Now installing BCALM........"
 cd ../../
 git clone --recursive https://github.com/GATB/bcalm
 cd bcalm
-mkdir build;  cd build;  cmake ..;  make -j 8 #after this we are inside build
+mkdir build;  cd build;  cmake ..;
+failureMessage cmake
+make -j 8 #after this we are inside build
+failureMessage bcalm_installation
 ln bcalm ../../bin/bcalmESS
 
 echo "Now installing MFCompress........"
 cd ../../
 cd src/mfc1.01/
 make -f Makefile.linux
+failureMessage MFC_installation
 ln MFCompressC ../../bin/mfcESS
 ln MFCompressD ../../bin/mfcdESS
 
 cd ../../
 export PATH="$PWD/bin:$PATH"
-#source ~/.bashrc
diff --git a/bin/essDecompress b/bin/essDecompress
--- a/bin/essDecompress
+++ b/bin/essDecompress
@@ -1,19 +1,52 @@
 #!/bin/bash
-
+function abspath {
+    if [[ -d "$1" ]]
+    then
+        pushd "$1" >/dev/null
+        pwd
+        popd >/dev/null
+    elif [[ -e "$1" ]]
+    then
+        pushd "$(dirname "$1")" >/dev/null
+        echo "$(pwd)/$(basename "$1")"
+        popd >/dev/null
+    else
+        echo "$1" does not exist! >&2
+        return 127
+    fi
+}
+failureMessage(){
+   if [ $? -eq 0 ]
+   then
+      echo "----------------------------"
+      echo "$1 completed successfully."
+      echo "----------------------------"
+   else
+      echo "----------------------------"
+      echo "$1 FAILED." 
+      echo "----------------------------"
+      exit
+   fi
+}
 set -e
-ENAME=$(basename $1 .essc)
+
+INPUTFILE=$(abspath $1)
+ENAME=$(basename $INPUTFILE .essc)
 ENAME="$ENAME.essd"
-mfcdESS $1
-MFCDFILE="$1.d"
+mfcdESS $INPUTFILE
+failureMessage mfcdESS
+MFCDFILE="$INPUTFILE.d"
 ISTIP=$(head -n 1 $MFCDFILE | cut -d'_' -f3)
 
 if [[ "$ISTIP" -eq "1" ]]; then
     cat $MFCDFILE | tr "a" "{" | tr "c" "}" | tr "g" "(" | tr "t" ")" | awk -F=' ' '{print ""$1}' > $ENAME
     essD $ENAME 
+    failureMessage essD
     mv kmers.esstip.spss $ENAME 
 else
     cat $MFCDFILE | tr "a" "+" | tr "c" "-" | tr "g" "[" | tr "t" "]" | awk -F=' ' '{print ""$1}' > $ENAME
     essD $ENAME 
+    failureMessage essD
     mv kmers.ess.spss $ENAME 
 fi
 
